import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";



const inter = Inter({ subsets: ["latin"] });
const popins = Poppins({
  weight: ['400', '700'],
  subsets: ["latin"]
});

export const metadata = {
  title: "Anas Next Hero",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

        <body className={popins.className}>
          <Navbar></Navbar>
          {children}
          <footer>
            This is footer
          </footer>
        </body>

    </html>
  );
}
